// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: snapshot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     uint64                 `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Crc32         uint32                 `protobuf:"varint,2,opt,name=crc32,proto3" json:"crc32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Header) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

type FullSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbHeader      *Header                `protobuf:"bytes,1,opt,name=db_header,json=dbHeader,proto3" json:"db_header,omitempty"`
	WalHeaders    []*Header              `protobuf:"bytes,2,rep,name=wal_headers,json=walHeaders,proto3" json:"wal_headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSnapshot) Reset() {
	*x = FullSnapshot{}
	mi := &file_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSnapshot) ProtoMessage() {}

func (x *FullSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSnapshot.ProtoReflect.Descriptor instead.
func (*FullSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *FullSnapshot) GetDbHeader() *Header {
	if x != nil {
		return x.DbHeader
	}
	return nil
}

func (x *FullSnapshot) GetWalHeaders() []*Header {
	if x != nil {
		return x.WalHeaders
	}
	return nil
}

type IncrementalSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalHeader     *Header                `protobuf:"bytes,1,opt,name=wal_header,json=walHeader,proto3" json:"wal_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementalSnapshot) Reset() {
	*x = IncrementalSnapshot{}
	mi := &file_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalSnapshot) ProtoMessage() {}

func (x *IncrementalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalSnapshot.ProtoReflect.Descriptor instead.
func (*IncrementalSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *IncrementalSnapshot) GetWalHeader() *Header {
	if x != nil {
		return x.WalHeader
	}
	return nil
}

type IncrementalFileSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalPaths      []string               `protobuf:"bytes,1,rep,name=wal_paths,json=walPaths,proto3" json:"wal_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementalFileSnapshot) Reset() {
	*x = IncrementalFileSnapshot{}
	mi := &file_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalFileSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalFileSnapshot) ProtoMessage() {}

func (x *IncrementalFileSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalFileSnapshot.ProtoReflect.Descriptor instead.
func (*IncrementalFileSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *IncrementalFileSnapshot) GetWalPaths() []string {
	if x != nil {
		return x.WalPaths
	}
	return nil
}

type NoopSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoopSnapshot) Reset() {
	*x = NoopSnapshot{}
	mi := &file_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoopSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoopSnapshot) ProtoMessage() {}

func (x *NoopSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoopSnapshot.ProtoReflect.Descriptor instead.
func (*NoopSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{4}
}

type SnapshotHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SnapshotHeader_Full
	//	*SnapshotHeader_Incremental
	//	*SnapshotHeader_IncrementalFile
	//	*SnapshotHeader_Noop
	Payload       isSnapshotHeader_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotHeader) Reset() {
	*x = SnapshotHeader{}
	mi := &file_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotHeader) ProtoMessage() {}

func (x *SnapshotHeader) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotHeader.ProtoReflect.Descriptor instead.
func (*SnapshotHeader) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotHeader) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SnapshotHeader) GetPayload() isSnapshotHeader_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotHeader) GetFull() *FullSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SnapshotHeader_Full); ok {
			return x.Full
		}
	}
	return nil
}

func (x *SnapshotHeader) GetIncremental() *IncrementalSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SnapshotHeader_Incremental); ok {
			return x.Incremental
		}
	}
	return nil
}

func (x *SnapshotHeader) GetIncrementalFile() *IncrementalFileSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SnapshotHeader_IncrementalFile); ok {
			return x.IncrementalFile
		}
	}
	return nil
}

func (x *SnapshotHeader) GetNoop() *NoopSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SnapshotHeader_Noop); ok {
			return x.Noop
		}
	}
	return nil
}

type isSnapshotHeader_Payload interface {
	isSnapshotHeader_Payload()
}

type SnapshotHeader_Full struct {
	Full *FullSnapshot `protobuf:"bytes,2,opt,name=full,proto3,oneof"`
}

type SnapshotHeader_Incremental struct {
	Incremental *IncrementalSnapshot `protobuf:"bytes,3,opt,name=incremental,proto3,oneof"`
}

type SnapshotHeader_IncrementalFile struct {
	IncrementalFile *IncrementalFileSnapshot `protobuf:"bytes,4,opt,name=incremental_file,json=incrementalFile,proto3,oneof"`
}

type SnapshotHeader_Noop struct {
	Noop *NoopSnapshot `protobuf:"bytes,5,opt,name=noop,proto3,oneof"`
}

func (*SnapshotHeader_Full) isSnapshotHeader_Payload() {}

func (*SnapshotHeader_Incremental) isSnapshotHeader_Payload() {}

func (*SnapshotHeader_IncrementalFile) isSnapshotHeader_Payload() {}

func (*SnapshotHeader_Noop) isSnapshotHeader_Payload() {}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\bsnapshot\"=\n" +
	"\x06Header\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x04R\tsizeBytes\x12\x14\n" +
	"\x05crc32\x18\x02 \x01(\rR\x05crc32\"p\n" +
	"\fFullSnapshot\x12-\n" +
	"\tdb_header\x18\x01 \x01(\v2\x10.snapshot.HeaderR\bdbHeader\x121\n" +
	"\vwal_headers\x18\x02 \x03(\v2\x10.snapshot.HeaderR\n" +
	"walHeaders\"F\n" +
	"\x13IncrementalSnapshot\x12/\n" +
	"\n" +
	"wal_header\x18\x01 \x01(\v2\x10.snapshot.HeaderR\twalHeader\"6\n" +
	"\x17IncrementalFileSnapshot\x12\x1b\n" +
	"\twal_paths\x18\x01 \x03(\tR\bwalPaths\"\x0e\n" +
	"\fNoopSnapshot\"\xb1\x02\n" +
	"\x0eSnapshotHeader\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12,\n" +
	"\x04full\x18\x02 \x01(\v2\x16.snapshot.FullSnapshotH\x00R\x04full\x12A\n" +
	"\vincremental\x18\x03 \x01(\v2\x1d.snapshot.IncrementalSnapshotH\x00R\vincremental\x12N\n" +
	"\x10incremental_file\x18\x04 \x01(\v2!.snapshot.IncrementalFileSnapshotH\x00R\x0fincrementalFile\x12,\n" +
	"\x04noop\x18\x05 \x01(\v2\x16.snapshot.NoopSnapshotH\x00R\x04noopB\t\n" +
	"\apayloadB-Z+github.com/rqlite/rqlite/v10/snapshot/protob\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snapshot_proto_goTypes = []any{
	(*Header)(nil),                  // 0: snapshot.Header
	(*FullSnapshot)(nil),            // 1: snapshot.FullSnapshot
	(*IncrementalSnapshot)(nil),     // 2: snapshot.IncrementalSnapshot
	(*IncrementalFileSnapshot)(nil), // 3: snapshot.IncrementalFileSnapshot
	(*NoopSnapshot)(nil),            // 4: snapshot.NoopSnapshot
	(*SnapshotHeader)(nil),          // 5: snapshot.SnapshotHeader
}
var file_snapshot_proto_depIdxs = []int32{
	0, // 0: snapshot.FullSnapshot.db_header:type_name -> snapshot.Header
	0, // 1: snapshot.FullSnapshot.wal_headers:type_name -> snapshot.Header
	0, // 2: snapshot.IncrementalSnapshot.wal_header:type_name -> snapshot.Header
	1, // 3: snapshot.SnapshotHeader.full:type_name -> snapshot.FullSnapshot
	2, // 4: snapshot.SnapshotHeader.incremental:type_name -> snapshot.IncrementalSnapshot
	3, // 5: snapshot.SnapshotHeader.incremental_file:type_name -> snapshot.IncrementalFileSnapshot
	4, // 6: snapshot.SnapshotHeader.noop:type_name -> snapshot.NoopSnapshot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	file_snapshot_proto_msgTypes[5].OneofWrappers = []any{
		(*SnapshotHeader_Full)(nil),
		(*SnapshotHeader_Incremental)(nil),
		(*SnapshotHeader_IncrementalFile)(nil),
		(*SnapshotHeader_Noop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
