// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: message.proto

package proto

import (
	proto "github.com/rqlite/rqlite/v8/command/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Type int32

const (
	Command_COMMAND_TYPE_UNKNOWN       Command_Type = 0
	Command_COMMAND_TYPE_GET_NODE_META Command_Type = 1
	Command_COMMAND_TYPE_EXECUTE       Command_Type = 2
	Command_COMMAND_TYPE_QUERY         Command_Type = 3
	Command_COMMAND_TYPE_BACKUP        Command_Type = 4
	Command_COMMAND_TYPE_LOAD          Command_Type = 5
	Command_COMMAND_TYPE_REMOVE_NODE   Command_Type = 6
	Command_COMMAND_TYPE_NOTIFY        Command_Type = 7
	Command_COMMAND_TYPE_JOIN          Command_Type = 8
	Command_COMMAND_TYPE_REQUEST       Command_Type = 9
	Command_COMMAND_TYPE_LOAD_CHUNK    Command_Type = 10
	Command_COMMAND_TYPE_BACKUP_STREAM Command_Type = 11
	Command_COMMAND_TYPE_STEPDOWN      Command_Type = 12
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0:  "COMMAND_TYPE_UNKNOWN",
		1:  "COMMAND_TYPE_GET_NODE_META",
		2:  "COMMAND_TYPE_EXECUTE",
		3:  "COMMAND_TYPE_QUERY",
		4:  "COMMAND_TYPE_BACKUP",
		5:  "COMMAND_TYPE_LOAD",
		6:  "COMMAND_TYPE_REMOVE_NODE",
		7:  "COMMAND_TYPE_NOTIFY",
		8:  "COMMAND_TYPE_JOIN",
		9:  "COMMAND_TYPE_REQUEST",
		10: "COMMAND_TYPE_LOAD_CHUNK",
		11: "COMMAND_TYPE_BACKUP_STREAM",
		12: "COMMAND_TYPE_STEPDOWN",
	}
	Command_Type_value = map[string]int32{
		"COMMAND_TYPE_UNKNOWN":       0,
		"COMMAND_TYPE_GET_NODE_META": 1,
		"COMMAND_TYPE_EXECUTE":       2,
		"COMMAND_TYPE_QUERY":         3,
		"COMMAND_TYPE_BACKUP":        4,
		"COMMAND_TYPE_LOAD":          5,
		"COMMAND_TYPE_REMOVE_NODE":   6,
		"COMMAND_TYPE_NOTIFY":        7,
		"COMMAND_TYPE_JOIN":          8,
		"COMMAND_TYPE_REQUEST":       9,
		"COMMAND_TYPE_LOAD_CHUNK":    10,
		"COMMAND_TYPE_BACKUP_STREAM": 11,
		"COMMAND_TYPE_STEPDOWN":      12,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3, 0}
}

type StepdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wait          bool                   `protobuf:"varint,1,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepdownRequest) Reset() {
	*x = StepdownRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepdownRequest) ProtoMessage() {}

func (x *StepdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepdownRequest.ProtoReflect.Descriptor instead.
func (*StepdownRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *StepdownRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type NodeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,2,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMeta) Reset() {
	*x = NodeMeta{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMeta) ProtoMessage() {}

func (x *NodeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMeta.ProtoReflect.Descriptor instead.
func (*NodeMeta) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMeta) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NodeMeta) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *NodeMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Command_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=cluster.Command_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*Command_ExecuteRequest
	//	*Command_QueryRequest
	//	*Command_BackupRequest
	//	*Command_LoadRequest
	//	*Command_RemoveNodeRequest
	//	*Command_NotifyRequest
	//	*Command_JoinRequest
	//	*Command_ExecuteQueryRequest
	//	*Command_LoadChunkRequest
	//	*Command_StepdownRequest
	Request       isCommand_Request `protobuf_oneof:"request"`
	Credentials   *Credentials      `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_COMMAND_TYPE_UNKNOWN
}

func (x *Command) GetRequest() isCommand_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Command) GetExecuteRequest() *proto.ExecuteRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_ExecuteRequest); ok {
			return x.ExecuteRequest
		}
	}
	return nil
}

func (x *Command) GetQueryRequest() *proto.QueryRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_QueryRequest); ok {
			return x.QueryRequest
		}
	}
	return nil
}

func (x *Command) GetBackupRequest() *proto.BackupRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_BackupRequest); ok {
			return x.BackupRequest
		}
	}
	return nil
}

func (x *Command) GetLoadRequest() *proto.LoadRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_LoadRequest); ok {
			return x.LoadRequest
		}
	}
	return nil
}

func (x *Command) GetRemoveNodeRequest() *proto.RemoveNodeRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_RemoveNodeRequest); ok {
			return x.RemoveNodeRequest
		}
	}
	return nil
}

func (x *Command) GetNotifyRequest() *proto.NotifyRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_NotifyRequest); ok {
			return x.NotifyRequest
		}
	}
	return nil
}

func (x *Command) GetJoinRequest() *proto.JoinRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_JoinRequest); ok {
			return x.JoinRequest
		}
	}
	return nil
}

func (x *Command) GetExecuteQueryRequest() *proto.ExecuteQueryRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_ExecuteQueryRequest); ok {
			return x.ExecuteQueryRequest
		}
	}
	return nil
}

func (x *Command) GetLoadChunkRequest() *proto.LoadChunkRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_LoadChunkRequest); ok {
			return x.LoadChunkRequest
		}
	}
	return nil
}

func (x *Command) GetStepdownRequest() *StepdownRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_StepdownRequest); ok {
			return x.StepdownRequest
		}
	}
	return nil
}

func (x *Command) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type isCommand_Request interface {
	isCommand_Request()
}

type Command_ExecuteRequest struct {
	ExecuteRequest *proto.ExecuteRequest `protobuf:"bytes,2,opt,name=execute_request,json=executeRequest,proto3,oneof"`
}

type Command_QueryRequest struct {
	QueryRequest *proto.QueryRequest `protobuf:"bytes,3,opt,name=query_request,json=queryRequest,proto3,oneof"`
}

type Command_BackupRequest struct {
	BackupRequest *proto.BackupRequest `protobuf:"bytes,5,opt,name=backup_request,json=backupRequest,proto3,oneof"`
}

type Command_LoadRequest struct {
	LoadRequest *proto.LoadRequest `protobuf:"bytes,6,opt,name=load_request,json=loadRequest,proto3,oneof"`
}

type Command_RemoveNodeRequest struct {
	RemoveNodeRequest *proto.RemoveNodeRequest `protobuf:"bytes,7,opt,name=remove_node_request,json=removeNodeRequest,proto3,oneof"`
}

type Command_NotifyRequest struct {
	NotifyRequest *proto.NotifyRequest `protobuf:"bytes,8,opt,name=notify_request,json=notifyRequest,proto3,oneof"`
}

type Command_JoinRequest struct {
	JoinRequest *proto.JoinRequest `protobuf:"bytes,9,opt,name=join_request,json=joinRequest,proto3,oneof"`
}

type Command_ExecuteQueryRequest struct {
	ExecuteQueryRequest *proto.ExecuteQueryRequest `protobuf:"bytes,10,opt,name=execute_query_request,json=executeQueryRequest,proto3,oneof"`
}

type Command_LoadChunkRequest struct {
	LoadChunkRequest *proto.LoadChunkRequest `protobuf:"bytes,11,opt,name=load_chunk_request,json=loadChunkRequest,proto3,oneof"`
}

type Command_StepdownRequest struct {
	StepdownRequest *StepdownRequest `protobuf:"bytes,12,opt,name=stepdown_request,json=stepdownRequest,proto3,oneof"`
}

func (*Command_ExecuteRequest) isCommand_Request() {}

func (*Command_QueryRequest) isCommand_Request() {}

func (*Command_BackupRequest) isCommand_Request() {}

func (*Command_LoadRequest) isCommand_Request() {}

func (*Command_RemoveNodeRequest) isCommand_Request() {}

func (*Command_NotifyRequest) isCommand_Request() {}

func (*Command_JoinRequest) isCommand_Request() {}

func (*Command_ExecuteQueryRequest) isCommand_Request() {}

func (*Command_LoadChunkRequest) isCommand_Request() {}

func (*Command_StepdownRequest) isCommand_Request() {}

type CommandExecuteResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Error         string                        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Response      []*proto.ExecuteQueryResponse `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	RaftIndex     uint64                        `protobuf:"varint,3,opt,name=raftIndex,proto3" json:"raftIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExecuteResponse) Reset() {
	*x = CommandExecuteResponse{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecuteResponse) ProtoMessage() {}

func (x *CommandExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecuteResponse.ProtoReflect.Descriptor instead.
func (*CommandExecuteResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *CommandExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandExecuteResponse) GetResponse() []*proto.ExecuteQueryResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CommandExecuteResponse) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type CommandQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Rows          []*proto.QueryRows     `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	RaftIndex     uint64                 `protobuf:"varint,3,opt,name=raftIndex,proto3" json:"raftIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandQueryResponse) Reset() {
	*x = CommandQueryResponse{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandQueryResponse) ProtoMessage() {}

func (x *CommandQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandQueryResponse.ProtoReflect.Descriptor instead.
func (*CommandQueryResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *CommandQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandQueryResponse) GetRows() []*proto.QueryRows {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *CommandQueryResponse) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type CommandRequestResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Error         string                        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Response      []*proto.ExecuteQueryResponse `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	RaftIndex     uint64                        `protobuf:"varint,3,opt,name=raftIndex,proto3" json:"raftIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequestResponse) Reset() {
	*x = CommandRequestResponse{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequestResponse) ProtoMessage() {}

func (x *CommandRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequestResponse.ProtoReflect.Descriptor instead.
func (*CommandRequestResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *CommandRequestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandRequestResponse) GetResponse() []*proto.ExecuteQueryResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CommandRequestResponse) GetRaftIndex() uint64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type CommandBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandBackupResponse) Reset() {
	*x = CommandBackupResponse{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandBackupResponse) ProtoMessage() {}

func (x *CommandBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandBackupResponse.ProtoReflect.Descriptor instead.
func (*CommandBackupResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *CommandBackupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandBackupResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandLoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandLoadResponse) Reset() {
	*x = CommandLoadResponse{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLoadResponse) ProtoMessage() {}

func (x *CommandLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLoadResponse.ProtoReflect.Descriptor instead.
func (*CommandLoadResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *CommandLoadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandLoadChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandLoadChunkResponse) Reset() {
	*x = CommandLoadChunkResponse{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLoadChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLoadChunkResponse) ProtoMessage() {}

func (x *CommandLoadChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLoadChunkResponse.ProtoReflect.Descriptor instead.
func (*CommandLoadChunkResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *CommandLoadChunkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandRemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRemoveNodeResponse) Reset() {
	*x = CommandRemoveNodeResponse{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRemoveNodeResponse) ProtoMessage() {}

func (x *CommandRemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*CommandRemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *CommandRemoveNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandNotifyResponse) Reset() {
	*x = CommandNotifyResponse{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandNotifyResponse) ProtoMessage() {}

func (x *CommandNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandNotifyResponse.ProtoReflect.Descriptor instead.
func (*CommandNotifyResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *CommandNotifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CommandJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Leader        string                 `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandJoinResponse) Reset() {
	*x = CommandJoinResponse{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandJoinResponse) ProtoMessage() {}

func (x *CommandJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandJoinResponse.ProtoReflect.Descriptor instead.
func (*CommandJoinResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *CommandJoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandJoinResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

type CommandStepdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStepdownResponse) Reset() {
	*x = CommandStepdownResponse{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStepdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStepdownResponse) ProtoMessage() {}

func (x *CommandStepdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStepdownResponse.ProtoReflect.Descriptor instead.
func (*CommandStepdownResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *CommandStepdownResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\acluster\x1a\x1bcommand/proto/command.proto\"%\n" +
	"\x0fStepdownRequest\x12\x12\n" +
	"\x04wait\x18\x01 \x01(\bR\x04wait\"E\n" +
	"\vCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"Y\n" +
	"\bNodeMeta\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fcommit_index\x18\x02 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x8a\t\n" +
	"\aCommand\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.cluster.Command.TypeR\x04type\x12B\n" +
	"\x0fexecute_request\x18\x02 \x01(\v2\x17.command.ExecuteRequestH\x00R\x0eexecuteRequest\x12<\n" +
	"\rquery_request\x18\x03 \x01(\v2\x15.command.QueryRequestH\x00R\fqueryRequest\x12?\n" +
	"\x0ebackup_request\x18\x05 \x01(\v2\x16.command.BackupRequestH\x00R\rbackupRequest\x129\n" +
	"\fload_request\x18\x06 \x01(\v2\x14.command.LoadRequestH\x00R\vloadRequest\x12L\n" +
	"\x13remove_node_request\x18\a \x01(\v2\x1a.command.RemoveNodeRequestH\x00R\x11removeNodeRequest\x12?\n" +
	"\x0enotify_request\x18\b \x01(\v2\x16.command.NotifyRequestH\x00R\rnotifyRequest\x129\n" +
	"\fjoin_request\x18\t \x01(\v2\x14.command.JoinRequestH\x00R\vjoinRequest\x12R\n" +
	"\x15execute_query_request\x18\n" +
	" \x01(\v2\x1c.command.ExecuteQueryRequestH\x00R\x13executeQueryRequest\x12I\n" +
	"\x12load_chunk_request\x18\v \x01(\v2\x19.command.LoadChunkRequestH\x00R\x10loadChunkRequest\x12E\n" +
	"\x10stepdown_request\x18\f \x01(\v2\x18.cluster.StepdownRequestH\x00R\x0fstepdownRequest\x126\n" +
	"\vcredentials\x18\x04 \x01(\v2\x14.cluster.CredentialsR\vcredentials\"\xe2\x02\n" +
	"\x04Type\x12\x18\n" +
	"\x14COMMAND_TYPE_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_GET_NODE_META\x10\x01\x12\x18\n" +
	"\x14COMMAND_TYPE_EXECUTE\x10\x02\x12\x16\n" +
	"\x12COMMAND_TYPE_QUERY\x10\x03\x12\x17\n" +
	"\x13COMMAND_TYPE_BACKUP\x10\x04\x12\x15\n" +
	"\x11COMMAND_TYPE_LOAD\x10\x05\x12\x1c\n" +
	"\x18COMMAND_TYPE_REMOVE_NODE\x10\x06\x12\x17\n" +
	"\x13COMMAND_TYPE_NOTIFY\x10\a\x12\x15\n" +
	"\x11COMMAND_TYPE_JOIN\x10\b\x12\x18\n" +
	"\x14COMMAND_TYPE_REQUEST\x10\t\x12\x1b\n" +
	"\x17COMMAND_TYPE_LOAD_CHUNK\x10\n" +
	"\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_BACKUP_STREAM\x10\v\x12\x19\n" +
	"\x15COMMAND_TYPE_STEPDOWN\x10\fB\t\n" +
	"\arequest\"\x87\x01\n" +
	"\x16CommandExecuteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x129\n" +
	"\bresponse\x18\x02 \x03(\v2\x1d.command.ExecuteQueryResponseR\bresponse\x12\x1c\n" +
	"\traftIndex\x18\x03 \x01(\x04R\traftIndex\"r\n" +
	"\x14CommandQueryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12&\n" +
	"\x04rows\x18\x02 \x03(\v2\x12.command.QueryRowsR\x04rows\x12\x1c\n" +
	"\traftIndex\x18\x03 \x01(\x04R\traftIndex\"\x87\x01\n" +
	"\x16CommandRequestResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x129\n" +
	"\bresponse\x18\x02 \x03(\v2\x1d.command.ExecuteQueryResponseR\bresponse\x12\x1c\n" +
	"\traftIndex\x18\x03 \x01(\x04R\traftIndex\"A\n" +
	"\x15CommandBackupResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"+\n" +
	"\x13CommandLoadResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"0\n" +
	"\x18CommandLoadChunkResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"1\n" +
	"\x19CommandRemoveNodeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"-\n" +
	"\x15CommandNotifyResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"C\n" +
	"\x13CommandJoinResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\tR\x06leader\"/\n" +
	"\x17CommandStepdownResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05errorB+Z)github.com/rqlite/rqlite/v8/cluster/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_message_proto_goTypes = []any{
	(Command_Type)(0),                  // 0: cluster.Command.Type
	(*StepdownRequest)(nil),            // 1: cluster.StepdownRequest
	(*Credentials)(nil),                // 2: cluster.Credentials
	(*NodeMeta)(nil),                   // 3: cluster.NodeMeta
	(*Command)(nil),                    // 4: cluster.Command
	(*CommandExecuteResponse)(nil),     // 5: cluster.CommandExecuteResponse
	(*CommandQueryResponse)(nil),       // 6: cluster.CommandQueryResponse
	(*CommandRequestResponse)(nil),     // 7: cluster.CommandRequestResponse
	(*CommandBackupResponse)(nil),      // 8: cluster.CommandBackupResponse
	(*CommandLoadResponse)(nil),        // 9: cluster.CommandLoadResponse
	(*CommandLoadChunkResponse)(nil),   // 10: cluster.CommandLoadChunkResponse
	(*CommandRemoveNodeResponse)(nil),  // 11: cluster.CommandRemoveNodeResponse
	(*CommandNotifyResponse)(nil),      // 12: cluster.CommandNotifyResponse
	(*CommandJoinResponse)(nil),        // 13: cluster.CommandJoinResponse
	(*CommandStepdownResponse)(nil),    // 14: cluster.CommandStepdownResponse
	(*proto.ExecuteRequest)(nil),       // 15: command.ExecuteRequest
	(*proto.QueryRequest)(nil),         // 16: command.QueryRequest
	(*proto.BackupRequest)(nil),        // 17: command.BackupRequest
	(*proto.LoadRequest)(nil),          // 18: command.LoadRequest
	(*proto.RemoveNodeRequest)(nil),    // 19: command.RemoveNodeRequest
	(*proto.NotifyRequest)(nil),        // 20: command.NotifyRequest
	(*proto.JoinRequest)(nil),          // 21: command.JoinRequest
	(*proto.ExecuteQueryRequest)(nil),  // 22: command.ExecuteQueryRequest
	(*proto.LoadChunkRequest)(nil),     // 23: command.LoadChunkRequest
	(*proto.ExecuteQueryResponse)(nil), // 24: command.ExecuteQueryResponse
	(*proto.QueryRows)(nil),            // 25: command.QueryRows
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: cluster.Command.type:type_name -> cluster.Command.Type
	15, // 1: cluster.Command.execute_request:type_name -> command.ExecuteRequest
	16, // 2: cluster.Command.query_request:type_name -> command.QueryRequest
	17, // 3: cluster.Command.backup_request:type_name -> command.BackupRequest
	18, // 4: cluster.Command.load_request:type_name -> command.LoadRequest
	19, // 5: cluster.Command.remove_node_request:type_name -> command.RemoveNodeRequest
	20, // 6: cluster.Command.notify_request:type_name -> command.NotifyRequest
	21, // 7: cluster.Command.join_request:type_name -> command.JoinRequest
	22, // 8: cluster.Command.execute_query_request:type_name -> command.ExecuteQueryRequest
	23, // 9: cluster.Command.load_chunk_request:type_name -> command.LoadChunkRequest
	1,  // 10: cluster.Command.stepdown_request:type_name -> cluster.StepdownRequest
	2,  // 11: cluster.Command.credentials:type_name -> cluster.Credentials
	24, // 12: cluster.CommandExecuteResponse.response:type_name -> command.ExecuteQueryResponse
	25, // 13: cluster.CommandQueryResponse.rows:type_name -> command.QueryRows
	24, // 14: cluster.CommandRequestResponse.response:type_name -> command.ExecuteQueryResponse
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[3].OneofWrappers = []any{
		(*Command_ExecuteRequest)(nil),
		(*Command_QueryRequest)(nil),
		(*Command_BackupRequest)(nil),
		(*Command_LoadRequest)(nil),
		(*Command_RemoveNodeRequest)(nil),
		(*Command_NotifyRequest)(nil),
		(*Command_JoinRequest)(nil),
		(*Command_ExecuteQueryRequest)(nil),
		(*Command_LoadChunkRequest)(nil),
		(*Command_StepdownRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
