// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: snapshot/stream_header.pb

package snapshot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncrementalSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *IncrementalSnapshot) Reset() {
	*x = IncrementalSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_stream_header_pb_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalSnapshot) ProtoMessage() {}

func (x *IncrementalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_stream_header_pb_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalSnapshot.ProtoReflect.Descriptor instead.
func (*IncrementalSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_stream_header_pb_rawDescGZIP(), []int{0}
}

func (x *IncrementalSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FullSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db   *FullSnapshot_DataInfo   `protobuf:"bytes,3,opt,name=db,proto3" json:"db,omitempty"`
	Wals []*FullSnapshot_DataInfo `protobuf:"bytes,4,rep,name=wals,proto3" json:"wals,omitempty"`
}

func (x *FullSnapshot) Reset() {
	*x = FullSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_stream_header_pb_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSnapshot) ProtoMessage() {}

func (x *FullSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_stream_header_pb_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSnapshot.ProtoReflect.Descriptor instead.
func (*FullSnapshot) Descriptor() ([]byte, []int) {
	return file_snapshot_stream_header_pb_rawDescGZIP(), []int{1}
}

func (x *FullSnapshot) GetDb() *FullSnapshot_DataInfo {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *FullSnapshot) GetWals() []*FullSnapshot_DataInfo {
	if x != nil {
		return x.Wals
	}
	return nil
}

type StreamHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*StreamHeader_IncrementalSnapshot
	//	*StreamHeader_FullSnapshot
	Payload isStreamHeader_Payload `protobuf_oneof:"payload"`
}

func (x *StreamHeader) Reset() {
	*x = StreamHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_stream_header_pb_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHeader) ProtoMessage() {}

func (x *StreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_stream_header_pb_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHeader.ProtoReflect.Descriptor instead.
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return file_snapshot_stream_header_pb_rawDescGZIP(), []int{2}
}

func (x *StreamHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (m *StreamHeader) GetPayload() isStreamHeader_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *StreamHeader) GetIncrementalSnapshot() *IncrementalSnapshot {
	if x, ok := x.GetPayload().(*StreamHeader_IncrementalSnapshot); ok {
		return x.IncrementalSnapshot
	}
	return nil
}

func (x *StreamHeader) GetFullSnapshot() *FullSnapshot {
	if x, ok := x.GetPayload().(*StreamHeader_FullSnapshot); ok {
		return x.FullSnapshot
	}
	return nil
}

type isStreamHeader_Payload interface {
	isStreamHeader_Payload()
}

type StreamHeader_IncrementalSnapshot struct {
	IncrementalSnapshot *IncrementalSnapshot `protobuf:"bytes,2,opt,name=incremental_snapshot,json=incrementalSnapshot,proto3,oneof"`
}

type StreamHeader_FullSnapshot struct {
	FullSnapshot *FullSnapshot `protobuf:"bytes,3,opt,name=full_snapshot,json=fullSnapshot,proto3,oneof"`
}

func (*StreamHeader_IncrementalSnapshot) isStreamHeader_Payload() {}

func (*StreamHeader_FullSnapshot) isStreamHeader_Payload() {}

type FullSnapshot_DataInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FullSnapshot_DataInfo) Reset() {
	*x = FullSnapshot_DataInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_stream_header_pb_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullSnapshot_DataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSnapshot_DataInfo) ProtoMessage() {}

func (x *FullSnapshot_DataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_stream_header_pb_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSnapshot_DataInfo.ProtoReflect.Descriptor instead.
func (*FullSnapshot_DataInfo) Descriptor() ([]byte, []int) {
	return file_snapshot_stream_header_pb_rawDescGZIP(), []int{1, 0}
}

func (x *FullSnapshot_DataInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_snapshot_stream_header_pb protoreflect.FileDescriptor

var file_snapshot_stream_header_pb_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x12, 0x08, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x13, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x94, 0x01, 0x0a, 0x0c, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x2f, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02,
	0x64, 0x62, 0x12, 0x33, 0x0a, 0x04, 0x77, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x6c,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x77, 0x61, 0x6c, 0x73, 0x1a, 0x1e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x14, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48,
	0x00, 0x52, 0x13, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x3d, 0x0a, 0x0d, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x6c, 0x6c, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x71, 0x6c, 0x69, 0x74, 0x65, 0x2f, 0x72, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x2f, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snapshot_stream_header_pb_rawDescOnce sync.Once
	file_snapshot_stream_header_pb_rawDescData = file_snapshot_stream_header_pb_rawDesc
)

func file_snapshot_stream_header_pb_rawDescGZIP() []byte {
	file_snapshot_stream_header_pb_rawDescOnce.Do(func() {
		file_snapshot_stream_header_pb_rawDescData = protoimpl.X.CompressGZIP(file_snapshot_stream_header_pb_rawDescData)
	})
	return file_snapshot_stream_header_pb_rawDescData
}

var file_snapshot_stream_header_pb_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_snapshot_stream_header_pb_goTypes = []interface{}{
	(*IncrementalSnapshot)(nil),   // 0: streamer.IncrementalSnapshot
	(*FullSnapshot)(nil),          // 1: streamer.FullSnapshot
	(*StreamHeader)(nil),          // 2: streamer.StreamHeader
	(*FullSnapshot_DataInfo)(nil), // 3: streamer.FullSnapshot.DataInfo
}
var file_snapshot_stream_header_pb_depIdxs = []int32{
	3, // 0: streamer.FullSnapshot.db:type_name -> streamer.FullSnapshot.DataInfo
	3, // 1: streamer.FullSnapshot.wals:type_name -> streamer.FullSnapshot.DataInfo
	0, // 2: streamer.StreamHeader.incremental_snapshot:type_name -> streamer.IncrementalSnapshot
	1, // 3: streamer.StreamHeader.full_snapshot:type_name -> streamer.FullSnapshot
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_snapshot_stream_header_pb_init() }
func file_snapshot_stream_header_pb_init() {
	if File_snapshot_stream_header_pb != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snapshot_stream_header_pb_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementalSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_stream_header_pb_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_stream_header_pb_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_stream_header_pb_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullSnapshot_DataInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_snapshot_stream_header_pb_msgTypes[2].OneofWrappers = []interface{}{
		(*StreamHeader_IncrementalSnapshot)(nil),
		(*StreamHeader_FullSnapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snapshot_stream_header_pb_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_stream_header_pb_goTypes,
		DependencyIndexes: file_snapshot_stream_header_pb_depIdxs,
		MessageInfos:      file_snapshot_stream_header_pb_msgTypes,
	}.Build()
	File_snapshot_stream_header_pb = out.File
	file_snapshot_stream_header_pb_rawDesc = nil
	file_snapshot_stream_header_pb_goTypes = nil
	file_snapshot_stream_header_pb_depIdxs = nil
}
