[[flags]]
name = "ExtensionPaths"
cli = "--extensions-path"
type = "stringslicesalue"
short_help = "Comma-delimited list of paths to SQLite extensions to be loaded"
long_help = """
Each element may be a directory path, zipfile, or tar.gz file. May not be set.
"""
default = ""

[[flags]]
name = "HTTPAddr"
cli = "--http-addr"
type = "string"
short_help = "Bind network address for the HTTP Server"
long_help = """
It never includes a trailing HTTP or HTTPS.
"""
default = "localhost:4001"

[[flags]]
name = "HTTPAdv"
cli = "--http-adv-addr"
type = "string"
short_help = "Advertised HTTP server network address"
long_help = """
If not set, same as HTTP server bind address.
"""
default = ""

[[flags]]
name = "HTTPAllowOrigin"
cli = "--http-allow-origin"
type = "string"
short_help = "Value to set for Access-Control-Allow-Origin HTTP header"
long_help = """
"""
default = ""

[[flags]]
name = "AuthFile"
cli = "--auth"
type = "string"
short_help = "Path to the authentication file"
long_help = """
If not set, authentication is not enabled.
"""
default = ""

[[flags]]
name = "AutoBackupFile"
cli = "--auto-backup"
type = "string"
short_help = "Path to the auto-backup file"
long_help = """
If not set, automatic backup is not enabled.
"""
default = ""

[[flags]]
name = "AutoRestoreFile"
cli = "--auto-restore"
type = "string"
short_help = "Path to the auto-restore file"
long_help = """
If not set, automatic restore is not enabled.
"""
default = ""

[[flags]]
name = "HTTPx509CACert"
cli = "--http-ca-cert"
type = "string"
short_help = "Path to the CA certificate file for HTTPS communications"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "HTTPx509Cert"
cli = "--http-cert"
type = "string"
short_help = "Path to the X509 certificate for the HTTP server"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "HTTPx509Key"
cli = "--http-key"
type = "string"
short_help = "Path to the private key for the HTTP server"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "HTTPVerifyClient"
cli = "--http-verify-client"
type = "bool"
short_help = "Whether the HTTP server should verify client certificates"
long_help = """
"""
default = false

[[flags]]
name = "NodeX509CACert"
cli = "--node-ca-cert"
type = "string"
short_help = "Path to the CA certificate file for inter-node communications"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "NodeX509Cert"
cli = "--node-cert"
type = "string"
short_help = "Path to the X509 certificate for the Raft server"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "NodeX509Key"
cli = "--node-key"
type = "string"
short_help = "Path to the X509 key for the Raft server"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "NoNodeVerify"
cli = "--node-no-verify"
type = "bool"
short_help = "Disables checking other nodes' X509 certificates for validity"
long_help = """
"""
default = false

[[flags]]
name = "NodeVerifyClient"
cli = "--node-verify-client"
type = "bool"
short_help = "Enable mutual TLS for node-to-node communication"
long_help = """
"""
default = false

[[flags]]
name = "NodeVerifyServerName"
cli = "--node-verify-server-name"
type = "string"
short_help = "Hostname to verify on certificates returned by nodes"
long_help = """
If NoNodeVerify is true, this field is ignored.
"""
default = ""

[[flags]]
name = "NodeID"
cli = "--node-id"
type = "string"
short_help = "Unique Raft ID for the node"
long_help = """
If not set, defaults to the advertised Raft address.
"""
default = ""

[[flags]]
name = "RaftAddr"
cli = "--raft-addr"
type = "string"
short_help = "Bind network address for the Raft server"
long_help = """
"""
default = "localhost:4002"

[[flags]]
name = "RaftAdv"
cli = "--raft-adv-addr"
type = "string"
short_help = "Advertised Raft server address"
long_help = """
If not set, same as Raft bind address.
"""
default = ""

[[flags]]
name = "JoinAddrs"
cli = "--join"
type = "string"
short_help = "List of Raft addresses to use for a join attempt"
long_help = """
Comma-delimited list of nodes in host:port format.
"""
default = ""

[[flags]]
name = "JoinAttempts"
cli = "--join-attempts"
type = "int"
short_help = "Number of times a node should attempt to join using a given address"
long_help = """
"""
default = 5

[[flags]]
name = "JoinInterval"
cli = "--join-interval"
type = "duration"
short_help = "Time between retrying failed join operations"
long_help = """
"""
default = "3s"

[[flags]]
name = "JoinAs"
cli = "--join-as"
type = "string"
short_help = "User to perform join attempts as"
long_help = """
If not set, joins anonymously.
"""
default = ""

[[flags]]
name = "BootstrapExpect"
cli = "--bootstrap-expect"
type = "int"
short_help = "Minimum number of nodes required for a bootstrap"
long_help = """
"""
default = 0

[[flags]]
name = "BootstrapExpectTimeout"
cli = "--bootstrap-expect-timeout"
type = "duration"
short_help = "Maximum time a bootstrap operation can take"
long_help = """
"""
default = "120s"

[[flags]]
name = "DiscoMode"
cli = "--disco-mode"
type = "string"
short_help = "Discovery mode"
long_help = """
If not set, no node discovery is performed.
"""
default = ""

[[flags]]
name = "DiscoKey"
cli = "--disco-key"
type = "string"
short_help = "Discovery prefix key"
long_help = """
"""
default = "rqlite"

[[flags]]
name = "DiscoConfig"
cli = "--disco-config"
type = "string"
short_help = "Path to discovery configuration file"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "OnDiskPath"
cli = "--on-disk-path"
type = "string"
short_help = "Path to the SQLite on-disk database file"
long_help = """
If not set, uses a file in the data directory.
"""
default = ""

[[flags]]
name = "FKConstraints"
cli = "--fk"
type = "bool"
short_help = "Enable SQLite foreign key constraints"
long_help = """
"""
default = false

[[flags]]
name = "AutoVacInterval"
cli = "--auto-vacuum-int"
type = "duration"
short_help = "Automatic VACUUM interval"
long_help = """
Use 0s to disable. If not set, automatic VACUUM is not enabled.
"""
default = "0s"

[[flags]]
name = "AutoOptimizeInterval"
cli = "--auto-optimize-int"
type = "duration"
short_help = "Automatic optimization interval"
long_help = """
Use 0h to disable.
"""
default = "24h"

[[flags]]
name = "RaftLogLevel"
cli = "--raft-log-level"
type = "string"
short_help = "Minimum logging level for the Raft subsystem"
long_help = """
"""
default = "WARN"

[[flags]]
name = "RaftNonVoter"
cli = "--raft-non-voter"
type = "bool"
short_help = "Configure as a non-voting node"
long_help = """
"""
default = false

[[flags]]
name = "RaftSnapThreshold"
cli = "--raft-snap"
type = "uint64"
short_help = "Number of outstanding log entries that trigger a snapshot"
long_help = """
"""
default = 8192

[[flags]]
name = "RaftSnapThresholdWALSize"
cli = "--raft-snap-wal-size"
type = "uint64"
short_help = "Size of a SQLite WAL file which triggers a snapshot"
long_help = """
Set to 0 to disable.
"""
default = 4194304

[[flags]]
name = "RaftSnapInterval"
cli = "--raft-snap-int"
type = "duration"
short_help = "Snapshot threshold check interval"
long_help = """
"""
default = "10s"

[[flags]]
name = "RaftLeaderLeaseTimeout"
cli = "--raft-leader-lease-timeout"
type = "duration"
short_help = "Leader lease timeout"
long_help = """
Use 0s for Raft default.
"""
default = "0s"

[[flags]]
name = "RaftHeartbeatTimeout"
cli = "--raft-timeout"
type = "duration"
short_help = "Heartbeat timeout for Raft consensus"
long_help = """
Specifies the time in follower state without contact from a Leader before the node attempts an election.
"""
default = "1s"

[[flags]]
name = "RaftElectionTimeout"
cli = "--raft-election-timeout"
type = "duration"
short_help = "Election timeout for Raft consensus"
long_help = """
Specifies the time in candidate state without contact from a Leader before the node attempts an election.
"""
default = "1s"

[[flags]]
name = "RaftApplyTimeout"
cli = "--raft-apply-timeout"
type = "duration"
short_help = "Log-apply timeout"
long_help = """
"""
default = "10s"

[[flags]]
name = "RaftShutdownOnRemove"
cli = "--raft-remove-shutdown"
type = "bool"
short_help = "Shutdown Raft if the node is removed from the cluster"
long_help = """
"""
default = false

[[flags]]
name = "RaftClusterRemoveOnShutdown"
cli = "--raft-cluster-remove-shutdown"
type = "bool"
short_help = "Node removes itself from the cluster on shutdown"
long_help = """
"""
default = false

[[flags]]
name = "RaftStepdownOnShutdown"
cli = "--raft-shutdown-stepdown"
type = "bool"
short_help = "Relinquish leadership on shutdown"
long_help = """
Enabled by default.
"""
default = true

[[flags]]
name = "RaftReapNodeTimeout"
cli = "--raft-reap-node-timeout"
type = "duration"
short_help = "Duration after which a non-reachable voting node is reaped"
long_help = """
If not set, no reaping takes place.
"""
default = "0h"

[[flags]]
name = "RaftReapReadOnlyNodeTimeout"
cli = "--raft-reap-read-only-node-timeout"
type = "duration"
short_help = "Duration after which a non-reachable non-voting node is reaped"
long_help = """
If not set, no reaping takes place.
"""
default = "0h"

[[flags]]
name = "ClusterConnectTimeout"
cli = "--cluster-connect-timeout"
type = "duration"
short_help = "Timeout when connecting to another node in the cluster"
long_help = """
"""
default = "30s"

[[flags]]
name = "WriteQueueCap"
cli = "--write-queue-capacity"
type = "int"
short_help = "Default capacity of execute queues"
long_help = """
"""
default = 1024

[[flags]]
name = "WriteQueueBatchSz"
cli = "--write-queue-batch-size"
type = "int"
short_help = "Default batch size for execute queues"
long_help = """
"""
default = 128

[[flags]]
name = "WriteQueueTimeout"
cli = "--write-queue-timeout"
type = "duration"
short_help = "Time after which data will be sent on execute queues if batch size isn't reached"
long_help = """
"""
default = "50ms"

[[flags]]
name = "WriteQueueTx"
cli = "--write-queue-tx"
type = "bool"
short_help = "Use a transaction when processing a queued write"
long_help = """
"""
default = false

[[flags]]
name = "CPUProfile"
cli = "--cpu-profile"
type = "string"
short_help = "Enable CPU profiling"
long_help = """
Path to file for CPU profiling information.
"""
default = ""

[[flags]]
name = "MemProfile"
cli = "--mem-profile"
type = "string"
short_help = "Enable memory profiling"
long_help = """
Path to file for memory profiling information.
"""
default = ""

[[flags]]
name = "TraceProfile"
cli = "--trace-profile"
type = "string"
short_help = "Enable trace profiling"
long_help = """
Path to file for trace profiling information.
"""
default = ""
