[[flags]]
name = "ExtensionPaths"
cli = "--extensions-path"
type = "stringslicesalue"
short_help = "Comma-delimited list of paths to directories, zipfiles, or tar.gz files containing SQLite extensions"
long_help = """
"""
default = ""

[[flags]]
name = "HTTPAddr"
cli = "--http-addr"
type = "string"
short_help = "HTTP server bind address. To enable HTTPS, set X.509 certificate and key"
long_help = """
This is the interace rqlited will listen on for API requests. 0.0.0.0 is an acceptable address and will mean that rqlited will listen on all interfaces.
"""
default = "localhost:4001"

[[flags]]
name = "HTTPAdv"
cli = "--http-adv-addr"
type = "string"
short_help = "Advertised HTTP server network address If not set, same as HTTP server bind address"
long_help = """
This is the HTTP API address an rqlited node will advertise to other nodes (and clients) as needed. This will need to be set if your rqlited node binds to all network addresses via 0.0.0.0, or if it binds to a private network address behind a firewall."
"""
default = ""

[[flags]]
name = "HTTPAllowOrigin"
cli = "--http-allow-origin"
type = "string"
short_help = "Value to set for Access-Control-Allow-Origin HTTP header"
long_help = """
You usually need to set this if if you're using a browser-based application to interfact with rqlite. You should set it to the the website that is serving the browser-based application.
"""
default = ""

[[flags]]
name = "AuthFile"
cli = "--auth"
type = "string"
short_help = "Path to the authentication file. If not set, authentication is not enabled"
long_help = """
"""
default = ""

[[flags]]
name = "AutoBackupFile"
cli = "--auto-backup"
type = "string"
short_help = "Path to the auto-backup file. If not set, automatic backup is not enabled"
long_help = """
"""
default = ""

[[flags]]
name = "AutoRestoreFile"
cli = "--auto-restore"
type = "string"
short_help = "Path to the auto-restore file. If not set, automatic restore is not enabled"
long_help = """
"""
default = ""

[[flags]]
name = "HTTPx509CACert"
cli = "--http-ca-cert"
type = "string"
short_help = "Path to the CA certificate file for HTTPS communications"
long_help = """
If this value is set rqlited will use this CA certificate to validate any other HTTPS certficate presented to it, if the node needs to contact another node's HTTP API. It also uses this CA to verify any X509 certificates presented to it by clients connecting to its HTTPS API.
"""
default = ""

[[flags]]
name = "HTTPx509Cert"
cli = "--http-cert"
type = "string"
short_help = "Path to the X509 certificate for the HTTP server. If not set HTTPS is not enabled"
long_help = """
This is the certificate rqlited will present to any client connecting to it via HTTPS.
"""
default = ""

[[flags]]
name = "HTTPx509Key"
cli = "--http-key"
type = "string"
short_help = "Path to the private key for the HTTPS server."
long_help = """
This is the private key corresponding to the x.509 certificate.
"""
default = ""

[[flags]]
name = "HTTPVerifyClient"
cli = "--http-verify-client"
type = "bool"
short_help = "Whether the HTTP server should verify client x509 certificates"
long_help = """
This allows you to control which clients can connect to the HTTPS API, as only clients presenting certificates that have been signed by the CA will be able to connect with rqlited.
"""
default = false

[[flags]]
name = "NodeX509CACert"
cli = "--node-ca-cert"
type = "string"
short_help = "Path to the CA certificate file for inter-node communications. May not be set"
long_help = """
If this path is set, and nodes enable TLS inter-node communications i.e. over the Raft TCP port, then the certificates presented by a node must be signed by the Certificate Authority.
"""
default = ""

[[flags]]
name = "NodeX509Cert"
cli = "--node-cert"
type = "string"
short_help = "Path to the x509 certificate for inter-node communications"
long_help = """
Setting this path enables TLS-encrypted inter-node when this node communicates with other nodes. Specifically this is the certificate presented by this node when another node connects to it using TLS. If not set the node does not enable TLS."
"""
default = ""

[[flags]]
name = "NodeX509Key"
cli = "--node-key"
type = "string"
short_help = "Path to the X509 key for inter-node communications"
long_help = """
This is the private key corresponding to the node's x509 certificate, which it uses for inter-node communications.
"""
default = ""

[[flags]]
name = "NoNodeVerify"
cli = "--node-no-verify"
type = "bool"
short_help = "Disables checking other nodes' X509 certificates for validity"
long_help = """
Validity is defined as signed by an acceptable CA, that the hostname in the certificate matches the hostname of the connecting node, and that the presented certificates are not expired.
"""
default = false

[[flags]]
name = "NodeVerifyClient"
cli = "--node-verify-client"
type = "bool"
short_help = "Enable mutual TLS for node-to-node communication"
long_help = """
This allows a node to control which other nodes can connect to it. Unless those other nodes present a certificate signed by an acceptable CA, the connection will be refused.
"""
default = false

[[flags]]
name = "NodeVerifyServerName"
cli = "--node-verify-server-name"
type = "string"
short_help = "Hostname to verify on certificates returned by nodes"
long_help = """
When node verifies a certificate it normally checks that the hostname in the certificate matches the hostname of the connecting node. This flags explicitly tells the node which hostname will actually be in the presented certificate. This allows you to sign a single certificate, with a single hostname, and distribute that to all nodes. It's mostly useful when enabling mutual TLS.
"""
default = ""

[[flags]]
name = "NodeID"
cli = "--node-id"
type = "string"
short_help = "Unique Raft ID for the node.If not set, defaults to the advertised Raft address."
long_help = """
While not required, providing an explicit ID to a node makes cluster management simpler. Once set a node's ID cannot change.
"""
default = ""

[[flags]]
name = "RaftAddr"
cli = "--raft-addr"
type = "string"
short_help = "Bind network address for the Raft server in the form address:port"
long_help = """
This is the interace rqlited will listen on for connections from other node. 0.0.0.0 is an acceptable address and will mean that rqlited will listen on all interfaces.
"""
default = "localhost:4002"

[[flags]]
name = "RaftAdv"
cli = "--raft-adv-addr"
type = "string"
short_help = "Advertised Raft server address. If not set, same as Raft server bind address"
long_help = """
This is the Raft address an rqlited node will advertise to other nodes. This will need to be set if your rqlited node binds to all network addresses via 0.0.0.0, or if it binds to a private network address behind a firewall."
"""
default = ""

[[flags]]
name = "JoinAddrs"
cli = "--join"
type = "string"
short_help = "List of Raft addresses to use for a join attempt. Comma-delimited list of nodes in host:port format"
long_help = """
The node will try each join addresss, one after the other, until one succeeds or the join-attempt limit is reached.
"""
default = ""

[[flags]]
name = "JoinAttempts"
cli = "--join-attempts"
type = "int"
short_help = "Number of times a node should attempt to join a cluster using a given address"
long_help = """
"""
default = 5

[[flags]]
name = "JoinInterval"
cli = "--join-interval"
type = "duration"
short_help = "Time between retrying failed join operations"
long_help = """
"""
default = "3s"

[[flags]]
name = "JoinAs"
cli = "--join-as"
type = "string"
short_help = "User to perform join attempts as. If not set, joins anonymously"
long_help = """
If joining a cluster requires credentials you can a tell a node to read those credentials from a credential file, for the specified user. By using this flag you can avoid setting credentials in the command line you pass to rqlited, which can expose those credentials if someone has access to the process table.
"""
default = ""

[[flags]]
name = "BootstrapExpect"
cli = "--bootstrap-expect"
type = "int"
short_help = "Minimum number of nodes required for a bootstrap"
long_help = """
This flag provides the number of expected nodes in the cluster. Either this value should not be provided or the value must agree with other nodes in the cluster. When provided, rqlite waits until the specified number of servers are available and then bootstraps the cluster. This allows an initial leader to be elected automatically.
"""
default = 0

[[flags]]
name = "BootstrapExpectTimeout"
cli = "--bootstrap-expect-timeout"
type = "duration"
short_help = "Maximum time a bootstrap operation can take"
long_help = """
If a bootstrap operation does not succeed with this time, cluster formation will abort.
"""
default = "120s"

[[flags]]
name = "DiscoMode"
cli = "--disco-mode"
type = "string"
short_help = "Discovery mode. If not set, no node discovery is performed"
long_help = """
"""
default = ""

[[flags]]
name = "DiscoKey"
cli = "--disco-key"
type = "string"
short_help = "Discovery prefix key"
long_help = """
This allows you to use the same Discovery infrastructure e.g. Consul with multiple different rqlite clusters. Each rqlite cluster can use a different prefix key to share Discovery information.
"""
default = "rqlite"

[[flags]]
name = "DiscoConfig"
cli = "--disco-config"
type = "string"
short_help = "Path to discovery configuration file"
long_help = """
May not be set.
"""
default = ""

[[flags]]
name = "OnDiskPath"
cli = "--on-disk-path"
type = "string"
short_help = "Path to the SQLite on-disk database file.If not set, uses a file in the data directory."
long_help = """
Generally speaking you shouldn't need to set this. Your system is easiest to manage if you let rqlite manage the SQLite database. However this can be useful under certain performance-sensitive scenarious.
"""
default = ""

[[flags]]
name = "FKConstraints"
cli = "--fk"
type = "bool"
short_help = "Enable SQLite foreign key constraints"
long_help = """
SQLite doesn't enable foreign key constraints by default. If you'd like rqlite to automatically do so then set this flag. This flag must be set on every node in your cluster.
"""
default = false

[[flags]]
name = "AutoVacInterval"
cli = "--auto-vacuum-int"
type = "duration"
short_help = "Automatic VACUUM interval. Use 0s to disable. If not set, automatic VACUUM is not enabled"
long_help = """
If set to a non-zero interval rqlite will execute 'VACUUM' on the specified interval. This can help reduce SQLite disk usage, but writes are blocked while a VACUUM takes place. See https://www.sqlite.org/lang_vacuum.html for more information.
"""
default = "0s"

[[flags]]
name = "AutoOptimizeInterval"
cli = "--auto-optimize-int"
type = "duration"
short_help = "Automatic optimization interval. Use 0h to disable"
long_help = """
If set to a non-zero interval rqlite will execute 'PRAGMA OPTIMIZE' on the specified interval. This can help SQLite query performance. See https://www.sqlite.org/pragma.html#pragma_optimize for more information.
"""
default = "24h"

[[flags]]
name = "RaftLogLevel"
cli = "--raft-log-level"
type = "string"
short_help = "Minimum logging level for the Raft subsystem"
long_help = """
Acceptble log levels are ERROR, WARN, INFO and DEBUG.
"""
default = "WARN"

[[flags]]
name = "RaftNonVoter"
cli = "--raft-non-voter"
type = "bool"
short_help = "Configure as a non-voting node"
long_help = """
Adding non-voting (also known as read-only) nodes can help scale out query performance. Read-only nodes don't particpate in the Raft consensus system, but do receive the same stream of updates from the Leader as voting nodes do.
"""
default = false

[[flags]]
name = "RaftSnapThreshold"
cli = "--raft-snap"
type = "uint64"
short_help = "Number of outstanding log entries that trigger a snapshot"
long_help = """
Snapshotting is a critical part of the Raft subsystem, which involves storing a copy of the SQLite database and then truncating the Raft log. Writes are blocked during the Snapshot process, but more regular snapshotting can mean faster start-up times, as there will generally be fewer logs to apply when a node restarts.
"""
default = 8192

[[flags]]
name = "RaftSnapThresholdWALSize"
cli = "--raft-snap-wal-size"
type = "uint64"
short_help = "Size of a SQLite WAL file which triggers a snapshot.Set to 0 to disable"
long_help = """
rqlite, by default, will also trigger a snapshot if the WAL gets larger than 4MB. Large SQLite WAL files can decrease query performance, and since snapshotting involves checkpointing the WAL file, snapshotting is an effective way to limit WAL size. However writes are blocked during the snapshotting process, so it's trade-off.
"""
default = 4194304

[[flags]]
name = "RaftSnapInterval"
cli = "--raft-snap-int"
type = "duration"
short_help = "Snapshot threshold check interval"
long_help = """
This controls how often the Raft subsystem will check if snapshotting is required, either due to the number of oustanding log entries, or due to WAL size.
"""
default = "10s"

[[flags]]
name = "RaftLeaderLeaseTimeout"
cli = "--raft-leader-lease-timeout"
type = "duration"
short_help = "Leader lease timeout. Use 0s for Raft default"
long_help = """
This is used to control how long the "lease" lasts for being the leader without being able to contact a quorum If a Leader reaches this interval without contact, it will step down as Leader.
"""
default = "0s"

[[flags]]
name = "RaftHeartbeatTimeout"
cli = "--raft-timeout"
type = "duration"
short_help = "Heartbeat timeout for Raft consensus"
long_help = """
Specifies the time a Follower will wait without contact from a Leader before the Follower initiates an election.
"""
default = "1s"

[[flags]]
name = "RaftElectionTimeout"
cli = "--raft-election-timeout"
type = "duration"
short_help = "Election timeout for Raft consensus"
long_help = """
Specifies the time a Candidate will wait without contact from a Leader before the Candidate initiates a new election.
"""
default = "1s"

[[flags]]
name = "RaftApplyTimeout"
cli = "--raft-apply-timeout"
type = "duration"
short_help = "Log-apply timeout"
long_help = """
"""
default = "10s"

[[flags]]
name = "RaftShutdownOnRemove"
cli = "--raft-remove-shutdown"
type = "bool"
short_help = "Shutdown Raft if the node is removed from the cluster"
long_help = """
"""
default = false

[[flags]]
name = "RaftClusterRemoveOnShutdown"
cli = "--raft-cluster-remove-shutdown"
type = "bool"
short_help = "Node removes itself from the cluster on shutdown"
long_help = """
"""
default = false

[[flags]]
name = "RaftStepdownOnShutdown"
cli = "--raft-shutdown-stepdown"
type = "bool"
short_help = "Relinquish leadership on shutdown. Enabled by default"
long_help = """
If a node is being shutdown, and it's the Leader, this helps minimize the time the cluster is without a Leader. The leader will stop accepting client requests, make sure the target server is up to date and starts the transfer with a _TimeoutNow_ message. This message has the same effect as if the election timeout on the target server fires.
"""
default = true

[[flags]]
name = "RaftReapNodeTimeout"
cli = "--raft-reap-node-timeout"
type = "duration"
short_help = "Duration after which a non-reachable voting node is reaped. If not set, no reaping takes place"
long_help = """
Use this feature with caution, otherwise you may reap a node which has simply become unreachable.
"""
default = "0h"

[[flags]]
name = "RaftReapReadOnlyNodeTimeout"
cli = "--raft-reap-read-only-node-timeout"
type = "duration"
short_help = "Duration after which a non-reachable non-voting node is reaped. If not set, no reaping takes place"
long_help = """
This can be useful if you have a deployment where non-voting nodes tend to come and go, and you want to avoid explicitly removing those nodes.
"""
default = "0h"

[[flags]]
name = "ClusterConnectTimeout"
cli = "--cluster-connect-timeout"
type = "duration"
short_help = "Timeout when connecting to another node in the cluster"
long_help = """
"""
default = "30s"

[[flags]]
name = "WriteQueueCap"
cli = "--write-queue-capacity"
type = "int"
short_help = "Default capacity of execute queues"
long_help = """
The larger this queue the more _Queued Write_ requests can be queued up internally by the node. This queue is asynchronously drained, as requests are transmitted through the Raft log. Anytime the queue is full further Queued Write requests are blocked.
"""
default = 1024

[[flags]]
name = "WriteQueueBatchSz"
cli = "--write-queue-batch-size"
type = "int"
short_help = "Default batch size for execute queues"
long_help = """
The larger the batch size the more statements will be contained in a single Raft log entry. However larger batches will consume more memory, and may introduce latency.
"""
default = 128

[[flags]]
name = "WriteQueueTimeout"
cli = "--write-queue-timeout"
type = "duration"
short_help = "Time after which data will be sent on execute queues if batch size isn't reached"
long_help = """
"""
default = "50ms"

[[flags]]
name = "WriteQueueTx"
cli = "--write-queue-tx"
type = "bool"
short_help = "Use a transaction when processing a queued write"
long_help = """
"""
default = false

[[flags]]
name = "CPUProfile"
cli = "--cpu-profile"
type = "string"
short_help = "Enable CPU profiling"
long_help = """
Path to file for CPU profiling information.
"""
default = ""

[[flags]]
name = "MemProfile"
cli = "--mem-profile"
type = "string"
short_help = "Enable memory profiling"
long_help = """
Path to file for memory profiling information.
"""
default = ""

[[flags]]
name = "TraceProfile"
cli = "--trace-profile"
type = "string"
short_help = "Enable trace profiling"
long_help = """
Path to file for trace profiling information.
"""
default = ""
