// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	QueryRequest
	QueryRow
	QueryResult
	QueryResponse
	ExecRequest
	ExecResult
	ExecResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryRequest_ReadConsistency int32

const (
	QueryRequest_NONE   QueryRequest_ReadConsistency = 0
	QueryRequest_WEAK   QueryRequest_ReadConsistency = 1
	QueryRequest_STRONG QueryRequest_ReadConsistency = 2
)

var QueryRequest_ReadConsistency_name = map[int32]string{
	0: "NONE",
	1: "WEAK",
	2: "STRONG",
}
var QueryRequest_ReadConsistency_value = map[string]int32{
	"NONE":   0,
	"WEAK":   1,
	"STRONG": 2,
}

func (x QueryRequest_ReadConsistency) String() string {
	return proto1.EnumName(QueryRequest_ReadConsistency_name, int32(x))
}
func (QueryRequest_ReadConsistency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

// The query statement
type QueryRequest struct {
	Stmt            []string                     `protobuf:"bytes,1,rep,name=stmt" json:"stmt,omitempty"`
	Tx              bool                         `protobuf:"varint,2,opt,name=tx" json:"tx,omitempty"`
	ReadConsistency QueryRequest_ReadConsistency `protobuf:"varint,3,opt,name=read_consistency,json=readConsistency,enum=proto.QueryRequest_ReadConsistency" json:"read_consistency,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto1.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryRequest) GetStmt() []string {
	if m != nil {
		return m.Stmt
	}
	return nil
}

func (m *QueryRequest) GetTx() bool {
	if m != nil {
		return m.Tx
	}
	return false
}

func (m *QueryRequest) GetReadConsistency() QueryRequest_ReadConsistency {
	if m != nil {
		return m.ReadConsistency
	}
	return QueryRequest_NONE
}

// The query row
type QueryRow struct {
	Values [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (m *QueryRow) Reset()                    { *m = QueryRow{} }
func (m *QueryRow) String() string            { return proto1.CompactTextString(m) }
func (*QueryRow) ProtoMessage()               {}
func (*QueryRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryRow) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

// The query result
type QueryResult struct {
	Columns []string    `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Types   []string    `protobuf:"bytes,2,rep,name=types" json:"types,omitempty"`
	Rows    []*QueryRow `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
	Time    float32     `protobuf:"fixed32,4,opt,name=time" json:"time,omitempty"`
	Error   string      `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto1.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryResult) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *QueryResult) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *QueryResult) GetRows() []*QueryRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *QueryResult) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *QueryResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// The query response
type QueryResponse struct {
	Results []*QueryResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	Time    float32        `protobuf:"fixed32,2,opt,name=time" json:"time,omitempty"`
	Error   string         `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Leader  string         `protobuf:"bytes,4,opt,name=leader" json:"leader,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto1.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *QueryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *QueryResponse) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

// The exec statement
type ExecRequest struct {
	Stmt []string `protobuf:"bytes,1,rep,name=stmt" json:"stmt,omitempty"`
	Tx   bool     `protobuf:"varint,2,opt,name=tx" json:"tx,omitempty"`
}

func (m *ExecRequest) Reset()                    { *m = ExecRequest{} }
func (m *ExecRequest) String() string            { return proto1.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()               {}
func (*ExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecRequest) GetStmt() []string {
	if m != nil {
		return m.Stmt
	}
	return nil
}

func (m *ExecRequest) GetTx() bool {
	if m != nil {
		return m.Tx
	}
	return false
}

// The exec result
type ExecResult struct {
	LastInsertId int64   `protobuf:"varint,1,opt,name=last_insert_id,json=lastInsertId" json:"last_insert_id,omitempty"`
	RowsAffected int64   `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected" json:"rows_affected,omitempty"`
	Time         float32 `protobuf:"fixed32,3,opt,name=time" json:"time,omitempty"`
	Error        string  `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *ExecResult) Reset()                    { *m = ExecResult{} }
func (m *ExecResult) String() string            { return proto1.CompactTextString(m) }
func (*ExecResult) ProtoMessage()               {}
func (*ExecResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExecResult) GetLastInsertId() int64 {
	if m != nil {
		return m.LastInsertId
	}
	return 0
}

func (m *ExecResult) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *ExecResult) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ExecResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// The exec response
type ExecResponse struct {
	Results []*ExecResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	Time    float32       `protobuf:"fixed32,2,opt,name=time" json:"time,omitempty"`
	Error   string        `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Leader  string        `protobuf:"bytes,4,opt,name=leader" json:"leader,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto1.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExecResponse) GetResults() []*ExecResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ExecResponse) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ExecResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ExecResponse) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func init() {
	proto1.RegisterType((*QueryRequest)(nil), "proto.QueryRequest")
	proto1.RegisterType((*QueryRow)(nil), "proto.QueryRow")
	proto1.RegisterType((*QueryResult)(nil), "proto.QueryResult")
	proto1.RegisterType((*QueryResponse)(nil), "proto.QueryResponse")
	proto1.RegisterType((*ExecRequest)(nil), "proto.ExecRequest")
	proto1.RegisterType((*ExecResult)(nil), "proto.ExecResult")
	proto1.RegisterType((*ExecResponse)(nil), "proto.ExecResponse")
	proto1.RegisterEnum("proto.QueryRequest_ReadConsistency", QueryRequest_ReadConsistency_name, QueryRequest_ReadConsistency_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RqliteService service

type RqliteServiceClient interface {
	// Query executes a statement that reads data.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Exec executes a statement that writes data.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type rqliteServiceClient struct {
	cc *grpc.ClientConn
}

func NewRqliteServiceClient(cc *grpc.ClientConn) RqliteServiceClient {
	return &rqliteServiceClient{cc}
}

func (c *rqliteServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/proto.RqliteService/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rqliteServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := grpc.Invoke(ctx, "/proto.RqliteService/Exec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RqliteService service

type RqliteServiceServer interface {
	// Query executes a statement that reads data.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Exec executes a statement that writes data.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
}

func RegisterRqliteServiceServer(s *grpc.Server, srv RqliteServiceServer) {
	s.RegisterService(&_RqliteService_serviceDesc, srv)
}

func _RqliteService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RqliteServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RqliteService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RqliteServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RqliteService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RqliteServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RqliteService/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RqliteServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RqliteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RqliteService",
	HandlerType: (*RqliteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _RqliteService_Query_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _RqliteService_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto1.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xb3, 0x92, 0xec, 0x38, 0xe3, 0xbf, 0x9d, 0x84, 0x22, 0x7a, 0x12, 0x72, 0x0f, 0x82,
	0x16, 0x83, 0xdd, 0xbe, 0x40, 0x28, 0xa6, 0x84, 0x82, 0x43, 0x37, 0x85, 0x1e, 0x8d, 0x2a, 0x4d,
	0x40, 0x20, 0x6b, 0x9d, 0xdd, 0x55, 0x6c, 0x1f, 0x4a, 0xe9, 0xbd, 0xaf, 0xd3, 0xf7, 0x2b, 0xbb,
	0x92, 0x13, 0xcb, 0xf8, 0x52, 0xc8, 0xc9, 0x3b, 0xdf, 0xee, 0xcc, 0xfc, 0xe6, 0x1b, 0x0b, 0xfa,
	0x8a, 0xe4, 0x63, 0x96, 0xd0, 0x64, 0x2d, 0x85, 0x16, 0xd8, 0xb2, 0x3f, 0xe1, 0x5f, 0x06, 0xbd,
	0xaf, 0x25, 0xc9, 0x1d, 0xa7, 0x87, 0x92, 0x94, 0x46, 0x04, 0x4f, 0xe9, 0x95, 0xf6, 0x59, 0xe0,
	0x46, 0x17, 0xdc, 0x9e, 0x71, 0x00, 0x8e, 0xde, 0xfa, 0x4e, 0xc0, 0xa2, 0x0e, 0x77, 0xf4, 0x16,
	0x17, 0x30, 0x92, 0x14, 0xa7, 0xcb, 0x44, 0x14, 0x2a, 0x53, 0x9a, 0x8a, 0x64, 0xe7, 0xbb, 0x01,
	0x8b, 0x06, 0xb3, 0x71, 0x55, 0x7d, 0x72, 0x58, 0x72, 0xc2, 0x29, 0x4e, 0x3f, 0x3d, 0x3f, 0xe5,
	0x43, 0xd9, 0x14, 0xc2, 0x29, 0x0c, 0x8f, 0xde, 0x60, 0x07, 0xbc, 0xc5, 0xed, 0x62, 0x3e, 0x3a,
	0x33, 0xa7, 0xef, 0xf3, 0xeb, 0x2f, 0x23, 0x86, 0x00, 0xed, 0xbb, 0x6f, 0xfc, 0x76, 0xf1, 0x79,
	0xe4, 0x84, 0x21, 0x74, 0xaa, 0x1e, 0x62, 0x83, 0xaf, 0xa1, 0xfd, 0x18, 0xe7, 0x25, 0x29, 0x0b,
	0xdd, 0xe3, 0x75, 0x14, 0xfe, 0x61, 0xd0, 0xad, 0x41, 0x54, 0x99, 0x6b, 0xf4, 0xe1, 0x3c, 0x11,
	0x79, 0xb9, 0x2a, 0x54, 0x3d, 0xdd, 0x3e, 0xc4, 0x2b, 0x68, 0xe9, 0xdd, 0x9a, 0x94, 0xef, 0x58,
	0xbd, 0x0a, 0x70, 0x0c, 0x9e, 0x14, 0x1b, 0xe5, 0xbb, 0x81, 0x1b, 0x75, 0x67, 0xc3, 0xc6, 0x68,
	0x62, 0xc3, 0xed, 0xa5, 0xf1, 0x4b, 0x67, 0x2b, 0xf2, 0xbd, 0x80, 0x45, 0x0e, 0xb7, 0x67, 0x53,
	0x8e, 0xa4, 0x14, 0xd2, 0x6f, 0x05, 0xcc, 0x94, 0xb3, 0x41, 0xf8, 0x0b, 0xfa, 0x7b, 0x9a, 0xb5,
	0x28, 0x14, 0xe1, 0x7b, 0x38, 0x97, 0x96, 0xac, 0xe2, 0xe9, 0xce, 0xb0, 0xe9, 0x9e, 0xb9, 0xe2,
	0xfb, 0x27, 0x4f, 0x8d, 0x9c, 0x53, 0x8d, 0xdc, 0x83, 0x46, 0xc6, 0x8f, 0x9c, 0xe2, 0x94, 0xa4,
	0x85, 0xba, 0xe0, 0x75, 0x14, 0x4e, 0xa1, 0x3b, 0xdf, 0x52, 0xf2, 0x1f, 0x9b, 0x0e, 0x7f, 0x33,
	0x80, 0x2a, 0xc7, 0x3a, 0xf8, 0x16, 0x06, 0x79, 0xac, 0xf4, 0x32, 0x2b, 0x14, 0x49, 0xbd, 0xcc,
	0x52, 0x9f, 0x05, 0x2c, 0x72, 0x79, 0xcf, 0xa8, 0x37, 0x56, 0xbc, 0x49, 0x71, 0x0c, 0x7d, 0x63,
	0xcd, 0x32, 0xbe, 0xbf, 0xa7, 0x44, 0x53, 0x6a, 0xeb, 0xb9, 0xbc, 0x67, 0xc4, 0xeb, 0x5a, 0x7b,
	0x1a, 0xc7, 0x3d, 0x35, 0x8e, 0x77, 0xe8, 0xdb, 0x4f, 0xe8, 0xd5, 0x08, 0x95, 0x6d, 0xef, 0x8e,
	0x6d, 0x7b, 0x55, 0xdb, 0xf6, 0x0c, 0xfa, 0x82, 0xae, 0xcd, 0xb6, 0xd0, 0xe7, 0x0f, 0x79, 0xa6,
	0xe9, 0xae, 0xfa, 0x7e, 0xf0, 0x23, 0xb4, 0xec, 0x82, 0xf0, 0xf2, 0xc4, 0x9f, 0xfd, 0xcd, 0xd5,
	0xd1, 0x0e, 0x2d, 0x73, 0x78, 0x86, 0x53, 0xf0, 0x0c, 0x1f, 0x62, 0x03, 0xb6, 0xca, 0xb9, 0x6c,
	0x0e, 0x50, 0xa7, 0xfc, 0x68, 0x5b, 0xf5, 0xc3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x06,
	0x4d, 0xa6, 0xba, 0x03, 0x00, 0x00,
}
