package main

const (
	RQLITE_DATA_DIR                 = "RQLITE_DATA_DIR"
	RQLITE_HTTP_ADDR                = "RQLITE_HTTP_ADDR"
	RQLITE_HTTP_ADV                 = "RQLITE_HTTP_ADV"
	RQLITE_AUTH_FILE                = "RQLITE_AUTH_FILE"
	RQLITE_X509_CERT                = "RQLITE_X509_CERT"
	RQLITE_X509_KEY                 = "RQLITE_X509_KEY"
	RQLITE_RAFT_ADDR                = "RQLITE_RAFT_ADDR"
	RQLITE_RAFT_ADV                 = "RQLITE_RAFT_ADV"
	RQLITE_JOIN_ADDR                = "RQLITE_JOIN_ADDR"
	RQLITE_NO_VERIFY                = "RQLITE_NO_VERIFY"
	RQLITE_EXPVAR                   = "RQLITE_EXPVAR"
	RQLITE_PPROF_ENABLED            = "RQLITE_PPROF_ENABLED"
	RQLITE_DSN                      = "RQLITE_DSN"
	RQLITE_ON_DISK                  = "RQLITE_ON_DISK"
	RQLITE_NO_VERIFY_SELECT         = "RQLITE_NO_VERIFY_SELECT"
	RQLITE_RAFT_SNAP_THRESHOLD      = "RQLITE_RAFT_SNAP_THRESHOLD"
	RQLITE_RAFT_HEARTBEAT_THRESHOLD = "RQLITE_RAFT_HEARTBEAT_THRESHOLD"
	RQLITE_CPU_PROFILE              = "RQLITE_CPU_PROFILE"
)
