// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: snapshot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotDBFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDBFile) Reset() {
	*x = SnapshotDBFile{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDBFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDBFile) ProtoMessage() {}

func (x *SnapshotDBFile) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDBFile.ProtoReflect.Descriptor instead.
func (*SnapshotDBFile) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotDBFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotDBFile) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type SnapshotWALFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotWALFile) Reset() {
	*x = SnapshotWALFile{}
	mi := &file_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotWALFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotWALFile) ProtoMessage() {}

func (x *SnapshotWALFile) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotWALFile.ProtoReflect.Descriptor instead.
func (*SnapshotWALFile) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotWALFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotWALFile) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type SnapshotInstall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbFile        *SnapshotDBFile        `protobuf:"bytes,2,opt,name=db_file,json=dbFile,proto3" json:"db_file,omitempty"`
	WalFiles      []*SnapshotWALFile     `protobuf:"bytes,3,rep,name=wal_files,json=walFiles,proto3" json:"wal_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInstall) Reset() {
	*x = SnapshotInstall{}
	mi := &file_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInstall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInstall) ProtoMessage() {}

func (x *SnapshotInstall) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInstall.ProtoReflect.Descriptor instead.
func (*SnapshotInstall) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotInstall) GetDbFile() *SnapshotDBFile {
	if x != nil {
		return x.DbFile
	}
	return nil
}

func (x *SnapshotInstall) GetWalFiles() []*SnapshotWALFile {
	if x != nil {
		return x.WalFiles
	}
	return nil
}

type SnapshotManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*SnapshotManifest_DbPath
	//	*SnapshotManifest_WalPath
	//	*SnapshotManifest_Install
	Type          isSnapshotManifest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotManifest) Reset() {
	*x = SnapshotManifest{}
	mi := &file_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotManifest) ProtoMessage() {}

func (x *SnapshotManifest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotManifest.ProtoReflect.Descriptor instead.
func (*SnapshotManifest) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotManifest) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *SnapshotManifest) GetType() isSnapshotManifest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SnapshotManifest) GetDbPath() *SnapshotDBFile {
	if x != nil {
		if x, ok := x.Type.(*SnapshotManifest_DbPath); ok {
			return x.DbPath
		}
	}
	return nil
}

func (x *SnapshotManifest) GetWalPath() *SnapshotWALFile {
	if x != nil {
		if x, ok := x.Type.(*SnapshotManifest_WalPath); ok {
			return x.WalPath
		}
	}
	return nil
}

func (x *SnapshotManifest) GetInstall() *SnapshotInstall {
	if x != nil {
		if x, ok := x.Type.(*SnapshotManifest_Install); ok {
			return x.Install
		}
	}
	return nil
}

type isSnapshotManifest_Type interface {
	isSnapshotManifest_Type()
}

type SnapshotManifest_DbPath struct {
	DbPath *SnapshotDBFile `protobuf:"bytes,2,opt,name=db_path,json=dbPath,proto3,oneof"`
}

type SnapshotManifest_WalPath struct {
	WalPath *SnapshotWALFile `protobuf:"bytes,3,opt,name=wal_path,json=walPath,proto3,oneof"`
}

type SnapshotManifest_Install struct {
	Install *SnapshotInstall `protobuf:"bytes,4,opt,name=install,proto3,oneof"`
}

func (*SnapshotManifest_DbPath) isSnapshotManifest_Type() {}

func (*SnapshotManifest_WalPath) isSnapshotManifest_Type() {}

func (*SnapshotManifest_Install) isSnapshotManifest_Type() {}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\tsnapshot2\"C\n" +
	"\x0eSnapshotDBFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\"D\n" +
	"\x0fSnapshotWALFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\"~\n" +
	"\x0fSnapshotInstall\x122\n" +
	"\adb_file\x18\x02 \x01(\v2\x19.snapshot2.SnapshotDBFileR\x06dbFile\x127\n" +
	"\twal_files\x18\x03 \x03(\v2\x1a.snapshot2.SnapshotWALFileR\bwalFiles\"\xe8\x01\n" +
	"\x10SnapshotManifest\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x124\n" +
	"\adb_path\x18\x02 \x01(\v2\x19.snapshot2.SnapshotDBFileH\x00R\x06dbPath\x127\n" +
	"\bwal_path\x18\x03 \x01(\v2\x1a.snapshot2.SnapshotWALFileH\x00R\awalPath\x126\n" +
	"\ainstall\x18\x04 \x01(\v2\x1a.snapshot2.SnapshotInstallH\x00R\ainstallB\x06\n" +
	"\x04typeB-Z+github.com/rqlite/rqlite/v9/snapshot2/protob\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_snapshot_proto_goTypes = []any{
	(*SnapshotDBFile)(nil),   // 0: snapshot2.SnapshotDBFile
	(*SnapshotWALFile)(nil),  // 1: snapshot2.SnapshotWALFile
	(*SnapshotInstall)(nil),  // 2: snapshot2.SnapshotInstall
	(*SnapshotManifest)(nil), // 3: snapshot2.SnapshotManifest
}
var file_snapshot_proto_depIdxs = []int32{
	0, // 0: snapshot2.SnapshotInstall.db_file:type_name -> snapshot2.SnapshotDBFile
	1, // 1: snapshot2.SnapshotInstall.wal_files:type_name -> snapshot2.SnapshotWALFile
	0, // 2: snapshot2.SnapshotManifest.db_path:type_name -> snapshot2.SnapshotDBFile
	1, // 3: snapshot2.SnapshotManifest.wal_path:type_name -> snapshot2.SnapshotWALFile
	2, // 4: snapshot2.SnapshotManifest.install:type_name -> snapshot2.SnapshotInstall
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	file_snapshot_proto_msgTypes[3].OneofWrappers = []any{
		(*SnapshotManifest_DbPath)(nil),
		(*SnapshotManifest_WalPath)(nil),
		(*SnapshotManifest_Install)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
