package wal

import (
	"encoding/binary"
	"errors"
	"expvar"
	"fmt"
	"io"
	"maps"
	"math"
	"sort"
	"time"
)

var (
	// ErrOpenTransaction is returned when the final frame in the WAL file is not a committing frame.
	ErrOpenTransaction = errors.New("open transaction at end of WAL file")
)

// CompactingFrameScanner implements WALIterator to iterate over compacted WAL
// frames starting from a given frame index. It scans all valid frames from the
// start position to the end of the WAL (or the first invalid frame), keeps only
// the latest version of each page (respecting transaction boundaries), and
// returns them in file offset order. If fullScan is false, frame checksums are
// not verified since the WAL file is trusted.
type CompactingFrameScanner struct {
	readSeeker io.ReadSeeker
	walReader  *Reader
	header     *WALHeader
	fullScan   bool
	start      int64

	frames cFrames
	fIdx   int
}

// NewCompactingFrameScanner creates a new CompactingFrameScanner that reads
// and compacts frames starting at the 0-based startFrame index, scanning to
// the end of the WAL or the first invalid frame. The WAL header is always read
// from offset 0 and is used to determine the page size (and therefore the frame
// size) for offset calculation.
//
// If fullScan is true, the scanner will perform a checksum validation on each frame.
// fullScan requires startFrame to be 0 so that running checksums can be validated
// from the beginning of the WAL.
//
// If fullScan is false, the scanner will only scan the file sufficiently to find the
// last valid frame for each page via a simple salt1 and salt2 match, without performing
// a full checksum validation. This is suitable when the WAL file is trusted (e.g. it's
// just been generated by SQLite and is known to a priori to be valid). This can be much
// faster for large WAL files, since it avoids reading the page data for each frame.
//
// Scanning stops at the first invalid frame (e.g. salt mismatch, checksum failure if
// applicable, or partial read).
func NewCompactingFrameScanner(r io.ReadSeeker, startFrame int64, fullScan bool) (*CompactingFrameScanner, error) {
	walReader := NewReader(r)
	if err := walReader.ReadHeader(); err != nil {
		return nil, err
	}

	pageSize := walReader.pageSize
	frameSize := int64(WALFrameHeaderSize) + int64(pageSize)

	if fullScan && startFrame != 0 {
		return nil, fmt.Errorf("fullScan requires startFrame to be 0, got %d", startFrame)
	}
	if startFrame < 0 {
		return nil, fmt.Errorf("startFrame (%d) must not be negative", startFrame)
	}

	s := &CompactingFrameScanner{
		readSeeker: r,
		walReader:  walReader,
		header: &WALHeader{
			Magic:     walReader.magic,
			Version:   WALSupportedVersion,
			PageSize:  pageSize,
			Seq:       walReader.seq,
			Salt1:     walReader.salt1,
			Salt2:     walReader.salt2,
			Checksum1: walReader.chksum1,
			Checksum2: walReader.chksum2,
		},
		fullScan: fullScan,
		start:    WALHeaderSize + startFrame*frameSize,
	}

	startT := time.Now()
	n, err := s.scan()
	if err != nil {
		stats.Add(compactScanErrors, 1)
		return nil, err
	}
	stats.Get(compactScanDuration).(*expvar.Int).Set(time.Since(startT).Milliseconds())
	stats.Get(compactFramesOutput).(*expvar.Int).Set(int64(len(s.frames)))
	if len(s.frames) > 0 {
		r := math.Round(float64(n)/float64(len(s.frames))*10) / 10
		stats.Get(compactFramesRatio).(*expvar.Float).Set(r)
	}
	return s, nil
}

// Header returns the WAL header.
func (s *CompactingFrameScanner) Header() (*WALHeader, error) {
	return s.header, nil
}

// Next returns the next compacted frame. Returns io.EOF when all frames
// have been read.
func (s *CompactingFrameScanner) Next() (*Frame, error) {
	if s.fIdx >= len(s.frames) {
		return nil, io.EOF
	}

	cf := s.frames[s.fIdx]
	data := make([]byte, s.header.PageSize)
	if _, err := s.readSeeker.Seek(cf.Offset+WALFrameHeaderSize, io.SeekStart); err != nil {
		return nil, err
	}
	if _, err := io.ReadFull(s.readSeeker, data); err != nil {
		return nil, err
	}
	s.fIdx++

	return &Frame{
		Pgno:   cf.Pgno,
		Commit: cf.Commit,
		Data:   data,
	}, nil
}

// Empty reports whether the scanner has zero frames to deliver.
func (s *CompactingFrameScanner) Empty() bool {
	return len(s.frames) == 0
}

// Bytes returns a byte slice containing the entire contents of the compacted WAL file.
// The byte slice is suitable for writing to a new WAL file. For large WAL files, this
// may consume a lot of memory, so it should be used with care. It's mostly intended for
// use in testing, where the WAL files are small.
func (s *CompactingFrameScanner) Bytes() ([]byte, error) {
	pageSz := int(s.header.PageSize)
	buf := make([]byte, WALHeaderSize+(len(s.frames)*WALFrameHeaderSize)+len(s.frames)*pageSz)
	s.header.Copy(buf)

	var bo binary.ByteOrder
	switch magic := s.header.Magic; magic {
	case 0x377f0682:
		bo = binary.LittleEndian
	case 0x377f0683:
		bo = binary.BigEndian
	default:
		return nil, fmt.Errorf("invalid wal header magic: %x", magic)
	}

	frmHdr := WALHeaderSize
	chksum1, chksum2 := s.header.Checksum1, s.header.Checksum2
	for _, frame := range s.frames {
		frmData := frmHdr + WALFrameHeaderSize

		binary.BigEndian.PutUint32(buf[frmHdr:], frame.Pgno)
		binary.BigEndian.PutUint32(buf[frmHdr+4:], frame.Commit)
		binary.BigEndian.PutUint32(buf[frmHdr+8:], s.header.Salt1)
		binary.BigEndian.PutUint32(buf[frmHdr+12:], s.header.Salt2)

		// Checksum of frame header: "...the first 8 bytes..."
		chksum1, chksum2 = WALChecksum(bo, chksum1, chksum2, buf[frmHdr:frmHdr+8])

		// Read the frame data.
		if _, err := s.readSeeker.Seek(frame.Offset+WALFrameHeaderSize, io.SeekStart); err != nil {
			return nil, fmt.Errorf("error seeking to frame offset: %s", err)
		}
		if _, err := io.ReadFull(s.readSeeker, buf[frmData:frmData+pageSz]); err != nil {
			return nil, fmt.Errorf("error reading frame data: %s", err)
		}

		// Update checksum using frame data.
		chksum1, chksum2 = WALChecksum(bo, chksum1, chksum2, buf[frmData:frmData+pageSz])
		binary.BigEndian.PutUint32(buf[frmHdr+16:], chksum1)
		binary.BigEndian.PutUint32(buf[frmHdr+20:], chksum2)

		frmHdr += WALFrameHeaderSize + pageSz
	}
	return buf, nil
}

// scan reads all valid frame headers from start to the end of the WAL and
// builds a compacted frame list, keeping only the latest version of each page.
// Only committed transactions are included.
func (s *CompactingFrameScanner) scan() (int64, error) {
	// Seek to the start position.
	if _, err := s.readSeeker.Seek(s.start, io.SeekStart); err != nil {
		return 0, fmt.Errorf("seek to start offset %d: %w", s.start, err)
	}

	var buf []byte
	if s.fullScan {
		buf = make([]byte, s.header.PageSize)
	}

	var framesInput int64
	waitingForCommit := false
	txFrames := make(map[uint32]*cFrame)
	frames := make(map[uint32]*cFrame)
	for {
		pgno, commit, err := s.walReader.ReadFrame(buf)
		if err == io.EOF {
			break
		} else if err != nil {
			return 0, err
		}
		framesInput++

		offset := s.start + s.walReader.Offset() - WALHeaderSize

		txFrames[pgno] = &cFrame{
			Pgno:   pgno,
			Commit: commit,
			Offset: offset,
		}

		if commit == 0 {
			waitingForCommit = true
			continue
		}
		waitingForCommit = false

		maps.Copy(frames, txFrames)
		clear(txFrames)
	}
	stats.Get(compactFramesInput).(*expvar.Int).Set(framesInput)

	if waitingForCommit {
		return framesInput, ErrOpenTransaction
	}

	s.frames = make(cFrames, 0, len(frames))
	for _, frame := range frames {
		s.frames = append(s.frames, frame)
	}
	sort.Sort(s.frames)
	return framesInput, nil
}

type cFrame struct {
	Pgno   uint32
	Commit uint32
	Offset int64
}

type cFrames []*cFrame

func (c cFrames) Len() int           { return len(c) }
func (c cFrames) Less(i, j int) bool { return c[i].Offset < c[j].Offset }
func (c cFrames) Swap(i, j int)      { c[i], c[j] = c[j], c[i] }
